name: rr-admin-actions
on:
  push:
    branches:
      - master
jobs:
  web-vue-job:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 14.x, 16.x, 18.x ]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
          - name: Set up work directory
          working-directory: ./smart-admin-web/javascript-ant-design-vue3
          - run: npm ci
          - run: npm run build:prod
  web-server-job:
    needs: web-vue-job
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 8
          uses: actions/setup-java@v3
          with:
            java-version: '8'
            distribution: 'adopt'
            cache: maven
        - name: Set up maven work directory
        working-directory: ./smart-admin-api
        - name: Build with Maven
          run: mvn -B package --file pom.xml

        # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
        - name: Update dependency graph
          uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
